import { Metadata } from "next";

export const metadata: Metadata = {
	title: {
		absolute: "",
		default: "Next.js Tutorial",
		template: "%s | Praveen",
	},
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<header style={{ backgroundColor: "lightgreen" }}>
					<p>Header</p>
				</header>
				{children}
				<footer style={{ backgroundColor: "orangered" }}>
					<p>Footer</p>
				</footer>
			</body>
		</html>
	);
}
